---
name: release

"on":
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Release gem
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{ secrets.RUBYGEMS_API_KEY }}

...
