---
name: release

"on":
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Release gem
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{ secrets.RUBYGEMS_API_KEY }}

...
