---
name: testing

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.1
          bundler: 1.17
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop

  spec:
    runs-on: ubuntu-latest
    needs: rubocop

    strategy:
      fail-fast: false

      matrix:
        ruby:
          - 2.1
          - 2.5
          - 2.7
          - 3.0
          - 3.1
          - 3.2
        rails:
          - 3.2
          - 4.2
          - 5.2
          - 6.1
          - 7.0
        exclude:
          - rails: 5.2
            ruby: 2.1
          - rails: 6.1
            ruby: 2.1
          - rails: 7.0
            ruby: 2.1
          - rails: 7.0
            ruby: 2.5
          - rails: 3.2
            ruby: 2.7
          - rails: 4.2
            ruby: 2.7
          - rails: 3.2
            ruby: 3.0
          - rails: 4.2
            ruby: 3.0
          - rails: 3.2
            ruby: 3.1
          - rails: 4.2
            ruby: 3.1
          - rails: 3.2
            ruby: 3.2
          - rails: 4.2
            ruby: 3.2

    steps:
      - name: Checkout source
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 1.17
          bundler-cache: true
        env:
          RAILS_VERSION: ${{ matrix.rails }}

      - name: Run rspec
        run: bundle exec rspec

...
